  version: '3.9'

  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper
      ports:
        - "2182:2181"   # Host:2182 -> Container:2181
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9999:9092"  # Host:9999 -> Container:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        # Listen on 0.0.0.0:9092 inside the container
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

        # Advertise the container's host/port as "kafka:9092" so other containers
        # in Docker can reach it. This prevents the "connection to broker localhost:9092 failed" warning.
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

        # For demo convenience: single-replica
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    python-app:
      build: .
      container_name: python-app
      depends_on:
        - kafka
      ports:
        - "7500:7500"  # Host:7500 -> Container:7500
      command: python -u app/main.py

